services:
  clearml:
    image: allegroai/clearml:latest
    container_name: clearml
    platform: linux/amd64
    ports:
      - "8080:8080"   # Web интерфейс
      - "8008:8008"   # API сервер
      - "8081:8081"   # File сервер
    environment:
      - CLEARML_APISERVER_HOST=http://clearml:8008
      - CLEARML_WEB_HOST=http://clearml:8080
      - CLEARML_FILES_HOST=http://clearml:8081
    volumes:
      - clearml_data:/data
      - clearml_config:/root/.clearml
    command: >
      clearml-server apiserver &
      clearml-server webserver &
      clearml-server fileserver &
      wait -n
    healthcheck:
      test: ["CMD", "curl", "-f", "http://clearml:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network


networks:
  app_network:
    driver: bridge
